import { Page, View, Text, StyleSheet } from "@react-pdf/renderer"
import type { ReactNode } from "react"
import { colors, fonts, fontSize } from "./theme"

const styles = StyleSheet.create({
  page: {
    backgroundColor: colors.background,
    paddingTop: 60,
    paddingBottom: 50,
    paddingHorizontal: 54, // ~0.75"
    fontFamily: fonts.sans,
  },
  header: {
    position: "absolute",
    top: 20,
    left: 54,
    right: 54,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingBottom: 8,
    borderBottomWidth: 1,
    borderBottomColor: colors.primary,
  },
  headerBrand: {
    fontFamily: fonts.serif,
    fontSize: fontSize.lg,
    color: colors.primary,
    fontWeight: 700,
  },
  footer: {
    position: "absolute",
    bottom: 20,
    left: 54,
    right: 54,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  footerText: {
    fontFamily: fonts.sans,
    fontSize: fontSize.xs,
    color: colors.textMuted,
  },
})

interface PdfPageShellProps {
  children: ReactNode
}

/**
 * Reusable page wrapper with fixed header ("Vera" branding + amber rule)
 * and footer (attribution + page number) on every page.
 */
export function PdfPageShell({ children }: PdfPageShellProps) {
  return (
    <Page size="LETTER" style={styles.page}>
      {/* Fixed header */}
      <View style={styles.header} fixed>
        <Text style={styles.headerBrand}>Vera</Text>
      </View>

      {/* Page content */}
      {children}

      {/* Fixed footer */}
      <View style={styles.footer} fixed>
        <Text style={styles.footerText}>Generated by Vera</Text>
        <Text
          style={styles.footerText}
          render={({ pageNumber, totalPages }) => `${pageNumber} / ${totalPages}`}
        />
      </View>
    </Page>
  )
}
