import type { StartupCardData } from "@/components/demian/startup-card"

export const demoStartups: StartupCardData[] = [
  {
    id: "1",
    startupName: "NeuralMed",
    founderName: "Sarah Chen",
    school: "Stanford University",
    sector: "HealthTech",
    stage: "Pre-Seed",
    location: "San Francisco, CA",
    pitchScore: 92,
    fitScore: 88,
    summary: "AI-powered diagnostics platform that reduces medical imaging analysis time by 80%. Currently piloting with 3 hospital systems and processing 10,000+ scans monthly.",
    tags: ["AI/ML", "Healthcare", "B2B", "SaaS"],
    imageColor: "oklch(0.35 0.1 160)",
  },
  {
    id: "2",
    startupName: "CarbonTrace",
    founderName: "Marcus Rivera",
    school: "MIT",
    sector: "CleanTech",
    stage: "Seed",
    location: "Boston, MA",
    pitchScore: 87,
    fitScore: 91,
    summary: "Supply chain carbon tracking and offset marketplace for mid-market enterprises. Onboarded 45 companies in first 6 months with $200K ARR.",
    tags: ["Climate", "Supply Chain", "Marketplace"],
    imageColor: "oklch(0.35 0.1 220)",
  },
  {
    id: "3",
    startupName: "Paylo",
    founderName: "Aisha Okonkwo",
    school: "Wharton",
    sector: "FinTech",
    stage: "Pre-Seed",
    location: "New York, NY",
    pitchScore: 84,
    fitScore: 79,
    summary: "Embedded payments infrastructure for African e-commerce platforms. Processing $500K monthly transaction volume across 12 merchant partners.",
    tags: ["Payments", "Africa", "Infrastructure"],
    imageColor: "oklch(0.35 0.1 80)",
  },
  {
    id: "4",
    startupName: "LabSync",
    founderName: "James Park",
    school: "Harvard",
    sector: "EdTech",
    stage: "Pre-Seed",
    location: "Cambridge, MA",
    pitchScore: 81,
    fitScore: 85,
    summary: "Collaborative lab management platform for university research teams. Used by 120+ research labs across 8 universities with 95% retention rate.",
    tags: ["Education", "Research", "Collaboration"],
    imageColor: "oklch(0.35 0.1 300)",
  },
  {
    id: "5",
    startupName: "VoxAI",
    founderName: "Elena Kowalski",
    school: "Carnegie Mellon",
    sector: "Enterprise",
    stage: "Seed",
    location: "Pittsburgh, PA",
    pitchScore: 89,
    fitScore: 82,
    summary: "Voice-first AI assistant for sales teams that auto-generates CRM entries, follow-ups, and deal intelligence from call recordings.",
    tags: ["AI", "Sales", "Enterprise", "Voice"],
    imageColor: "oklch(0.35 0.15 30)",
  },
  {
    id: "6",
    startupName: "Greenfield",
    founderName: "Tom Nakamura",
    school: "UC Berkeley",
    sector: "AgTech",
    stage: "Pre-Seed",
    location: "Davis, CA",
    pitchScore: 78,
    fitScore: 74,
    summary: "Precision agriculture platform using satellite imagery and IoT sensors to optimize water usage and crop yields for small-scale farmers.",
    tags: ["Agriculture", "IoT", "Sustainability"],
    imageColor: "oklch(0.35 0.12 140)",
  },
]

export const demoInvestors = [
  {
    id: "1",
    name: "Sequoia Scout Fund",
    contact: "Michael Zhang",
    focus: ["AI/ML", "HealthTech", "Enterprise"],
    stage: "Pre-Seed to Series A",
    checkSize: "$100K - $500K",
    location: "San Francisco",
    avatar: "S",
  },
  {
    id: "2",
    name: "Greenlight Ventures",
    contact: "Rebecca Torres",
    focus: ["CleanTech", "Climate", "AgTech"],
    stage: "Seed",
    checkSize: "$250K - $1M",
    location: "Boston",
    avatar: "G",
  },
  {
    id: "3",
    name: "TechBridge Capital",
    contact: "David Kim",
    focus: ["FinTech", "Payments", "Infrastructure"],
    stage: "Pre-Seed to Seed",
    checkSize: "$50K - $300K",
    location: "New York",
    avatar: "T",
  },
]

export const demoFeedback = {
  overallScore: 87,
  fitScore: 82,
  percentile: 94,
  investorViews: 23,
  strengths: [
    "Clear problem-solution fit with quantified market opportunity",
    "Strong traction metrics with 10K+ monthly active users",
    "Experienced founding team with relevant domain expertise",
    "Defensible technology with pending patent applications",
  ],
  weaknesses: [
    "Unit economics need clearer breakdown at scale",
    "Competitive landscape section could be more thorough",
    "Go-to-market strategy lacks specific channel partnerships",
    "Financial projections should include sensitivity analysis",
  ],
  improvements: [
    { label: "Add competitive moat slide", done: true },
    { label: "Include unit economics breakdown", done: true },
    { label: "Add customer testimonials", done: false },
    { label: "Clarify go-to-market channels", done: false },
    { label: "Show projected runway with raise", done: false },
  ],
  summary:
    "Your pitch demonstrates a strong understanding of the market opportunity and has compelling traction data. The AI analysis shows high investor-readiness with particularly strong scores in problem definition and team credibility. Key areas for improvement include deeper competitive analysis and clearer financial projections.",
}

export const demoActivity = [
  { type: "view", message: "Sequoia Scout Fund viewed your pitch", time: "2 hours ago" },
  { type: "score", message: "Pitch score updated: 85 -> 87", time: "5 hours ago" },
  { type: "match", message: "New investor match: Greenlight Ventures", time: "1 day ago" },
  { type: "feedback", message: "AI feedback refreshed for v3 of your deck", time: "2 days ago" },
  { type: "view", message: "TechBridge Capital viewed your pitch", time: "3 days ago" },
]
